In [2]:
import torch
import torch.nn as nn

batch_size = 3
t = 6

# Create random tensor of shape (batch_size, t, t)
x = torch.rand(batch_size, t, t)

# Create indices tensor for the upper triangular part of the tensor
indices = torch.triu_indices(t, t, offset=1)

# Set the indices of the upper triangular part of the mask tensor to 0
x[:, indices[0], indices[1]] = 0

print(x)
print(indices[0])
print(indices[1])
print(indices.shape)

tensor([[[0.8902, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2857, 0.2608, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.8455, 0.0122, 0.2208, 0.0000, 0.0000, 0.0000],
         [0.9623, 0.3989, 0.0183, 0.2763, 0.0000, 0.0000],
         [0.6193, 0.4517, 0.0257, 0.0219, 0.0510, 0.0000],
         [0.7650, 0.8960, 0.5462, 0.8789, 0.7664, 0.4872]],

        [[0.7525, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0029, 0.4277, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2925, 0.7121, 0.0921, 0.0000, 0.0000, 0.0000],
         [0.3663, 0.5060, 0.3170, 0.6980, 0.0000, 0.0000],
         [0.2507, 0.5361, 0.8265, 0.2580, 0.5119, 0.0000],
         [0.4410, 0.1981, 0.5014, 0.7222, 0.4464, 0.7979]],

        [[0.8413, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.6445, 0.8903, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.6733, 0.8247, 0.0193, 0.0000, 0.0000, 0.0000],
         [0.1439, 0.5193, 0.5362, 0.1753, 0.0000, 0.0000],
         [0.1593, 0.2054, 0.0255, 0.0955, 0.6057, 0.

In [25]:
# Test masked_fill
x = torch.rand(batch_size, t, t)

# Create a mask tensor of shape (t, t) with 0s (aka False) in the upper triangular part (excluding the diagonal)
mask = torch.tril(torch.ones(t, t))

# Set the indices of the upper triangular part of the mask tensor to 0
# x[:, mask] = 0
x = x.masked_fill(mask==0, 0)

print(x)
print(mask)
print(mask.shape)


tensor([[[0.8579, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.1946, 0.6119, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.3645, 0.1164, 0.1881, 0.0000, 0.0000, 0.0000],
         [0.9176, 0.1671, 0.8793, 0.9909, 0.0000, 0.0000],
         [0.3463, 0.8334, 0.9034, 0.5589, 0.9168, 0.0000],
         [0.6506, 0.2720, 0.2007, 0.3817, 0.1571, 0.7139]],

        [[0.2397, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.9893, 0.0637, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.0565, 0.4498, 0.2338, 0.0000, 0.0000, 0.0000],
         [0.9958, 0.2922, 0.9665, 0.3136, 0.0000, 0.0000],
         [0.6742, 0.2909, 0.1451, 0.2375, 0.7532, 0.0000],
         [0.6899, 0.9502, 0.4883, 0.4775, 0.6723, 0.2846]],

        [[0.4768, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.2574, 0.9705, 0.0000, 0.0000, 0.0000, 0.0000],
         [0.5314, 0.1295, 0.4172, 0.0000, 0.0000, 0.0000],
         [0.0531, 0.0637, 0.7375, 0.6373, 0.0000, 0.0000],
         [0.4622, 0.5365, 0.6750, 0.3619, 0.7400, 0.

Expand vector to a matrix by repeating the vector elements.

In [9]:
# Test masked_fill
x = torch.rand(batch_size, t, t)

attention_mask = torch.rand((batch_size, t)).unsqueeze(-2).repeat(1, t, 1)
attention_mask = torch.randint(0, 2, (batch_size, t)).unsqueeze(-2).repeat(1, t, 1)

print(attention_mask.shape)
print(x.shape)

x[attention_mask == 0] = 0

print(x)
print(attention_mask)


torch.Size([3, 6, 6])
torch.Size([3, 6, 6])
tensor([[[0.0000, 0.8089, 0.7607, 0.0000, 0.0000, 0.7684],
         [0.0000, 0.8069, 0.0068, 0.0000, 0.0000, 0.3775],
         [0.0000, 0.4450, 0.3432, 0.0000, 0.0000, 0.3333],
         [0.0000, 0.4341, 0.5587, 0.0000, 0.0000, 0.2143],
         [0.0000, 0.6526, 0.0385, 0.0000, 0.0000, 0.1547],
         [0.0000, 0.8197, 0.2559, 0.0000, 0.0000, 0.1664]],

        [[0.1825, 0.0000, 0.0000, 0.0342, 0.0000, 0.0000],
         [0.8548, 0.0000, 0.0000, 0.4717, 0.0000, 0.0000],
         [0.9553, 0.0000, 0.0000, 0.2179, 0.0000, 0.0000],
         [0.3062, 0.0000, 0.0000, 0.7283, 0.0000, 0.0000],
         [0.0136, 0.0000, 0.0000, 0.7003, 0.0000, 0.0000],
         [0.0441, 0.0000, 0.0000, 0.5844, 0.0000, 0.0000]],

        [[0.3532, 0.0000, 0.3193, 0.0000, 0.0000, 0.0000],
         [0.1192, 0.0000, 0.7664, 0.0000, 0.0000, 0.0000],
         [0.3210, 0.0000, 0.5438, 0.0000, 0.0000, 0.0000],
         [0.3891, 0.0000, 0.7150, 0.0000, 0.0000, 0.0000],
        